name: orangery
description: 'Orangery'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # для навигации
  auto_route: ^5.0.4
  auto_route_generator: 5.0.3
  build_runner: ^2.3.3

  # MVVM
  stacked: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/

  uses-material-design: true
